apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-grafana
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
